# netlify.toml

[build]
  # Specifies the directory where your build commands will run
  command="npm run build"
  base = "."
  # Specifies the directory that contains your production-ready HTML files
  publish = "views"
  # Specifies the directory where your build command is run
  command = "node server.js"
  # Specifies the directory that contains your source files
  functions = "functions" # If you have serverless functions

[build.environment]
  # Environment variables for MongoDB connection and session secret
  MONGODB_URI = "mongodb+srv://arrearbatch:Kareoss45@cluster0.gkwgzu9.mongodb.net/?retryWrites=true&w=majority"
  SESSION_SECRET = "Osos@4545niThin@4545"

# Add any additional configurations here as needed
